name: "Check Commits"

on:
    pull_request:

jobs:
    convetional-commits:
        name: "Conventional Commits"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"
                with:
                    fetch-depth: 0

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    php-version: "8.0"
                    ini-values: memory_limit=-1

            -   name: "Cache dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-8.0"
                    restore-keys: "php-8.0"

            -   name: "Install dependencies"
                run: "composer install --no-interaction --no-progress --no-suggest"

            -   name: "Check commits"
                run: "./bin/conventional-commits validate:commit -vv remotes/origin/$GITHUB_BASE_REF...remotes/origin/$GITHUB_HEAD_REF"
