name: "Static Analysis by Psalm"

on:
    pull_request:
    push:
        branches:
            - master
            - release/*

jobs:
    static-analysis-psalm:
        name: "Static Analysis by Psalm"
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    php-version: "8.0"
                    ini-values: memory_limit=-1

            -   name: "Cache dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-8.0-ubuntu"
                    restore-keys: "php-8.0-ubuntu"

            -   name: "Install dependencies"
                run: "composer install --no-interaction --no-progress"

            -   name: "psalm"
                run: vendor/bin/psalm --shepherd --stats
